cmake_minimum_required(VERSION 3.24)
project(KharvoxStaticLoader LANGUAGES C CXX)
set(DYNAMIC_LOADER OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_API_LAYERS OFF CACHE BOOL "" FORCE)
set(BUILD_CONFORMANCE_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_SDK_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_WITH_SYSTEM_JSONCPP OFF CACHE BOOL "" FORCE)
set(BUILD_WITH_STD_FILESYSTEM OFF CACHE BOOL "" FORCE)
add_subdirectory("${OPENXR_SOURCE_DIR}" sdk)
set_target_properties(openxr_loader PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>"
  INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
target_compile_options(openxr_loader PRIVATE $<$<CONFIG:Release>:/O1> $<$<CONFIG:Release>:/Gy> $<$<CONFIG:Release>:/Gw>)
